
jwt:
  signing-key: 'inwind'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'qmPlus'

mysql:
  host: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'inwind_blog'
  username: 'root'
  password: 'mysql'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: '123456'